IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Registration Open</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/classes/WebinarListController.cls
/**
 * Created by nnoman on 08.07.2022.
 */

public with sharing class WebinarListController
{
    @AuraEnabled
    public static Webinar__c[] getPendingWebinars(String queryLimit)
    {
        return [
                SELECT Name,Description__c,Cost__c,Status__c,Approval_Status__c
                FROM Webinar__c
                WHERE Approval_Status__c = 'Pending'
                LIMIT :Integer.valueOf(queryLimit)
        ];
    }
    @AuraEnabled
    public static Webinar__c changeWebinarStatus(Id webinarId,String status)
    {
        Webinar__c wb = [SELECT Id FROM Webinar__c WHERE Id=:webinarId];
        wb.Approval_Status__c=status;
        update wb;
        return wb;
    }
    @AuraEnabled
    public static Webinar__c[] getAllWebinars()
    {
        return [
                SELECT Name,Description__c,Cost__c,Status__c,Approval_Status__c,Type__c
                FROM Webinar__c
        ];
    }

    @AuraEnabled
    public static Webinar__c[] getFilteredWebinars(Map<String,String> filterMap)
    {
        String filterPart='';

        if(filterMap.size()>0)
            filterPart += ' WHERE ';

        List<String> filterList=new List<String>();
        for(String key : filterMap.keySet())
        {
            filterList.add(key + ' LIKE \'%' + String.escapeSingleQuotes(filterMap.get(key))  + '%\'');
        }
        String finalString = String.join(filterList,' AND ');
        System.debug(finalString);
        return
                Database.query(
                        'SELECT Name,Description__c,Cost__c,Status__c,Approval_Status__c,Type__c ' +
                        'FROM Webinar__c'+
                         finalString
                )
        ;
    }

}