IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/Webinar_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Webinar Team Member</description>
    <label>Webinar Team Member</label>
    <nameField>
        <label>Webinar Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinar Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/fields/Related_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Related_Webinar__c</fullName>
    <label>Related Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Team Members</relationshipLabel>
    <relationshipName>Webinar_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/classes/TEST_WebinarEmailNotificationScheduler.cls
/**
 * Created by nnoman on 14.07.2022.
 */
@IsTest
public with sharing class TEST_WebinarEmailNotificationScheduler
{
    @TestSetup
    private static void makeData()
    {
//        Webinar__c webinar = new Webinar__c();
//        webinar.Start_Date__c=Date.today().addDays(1);
//        insert webinar;
//
//        Contact contact= new Contact();
//////        create contact
////        contact.MailingCity='lol';
////        contact.MailingCountry='lol';
////        contact.MailingCountryCode='pl';
////        contact.MailingStreet='lol';
//        insert contact;
//
//        Webinar_Team_Member__c webinarTeamMember = new Webinar_Team_Member__c();
//        webinarTeamMember.Related_Webinar__c=webinar.Id;
//        webinarTeamMember.Contact__c=contact.Id;

    }

//    @IsTest
//    priv
}