IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/Webinar_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Webinar Team Member</description>
    <label>Webinar Team Member</label>
    <nameField>
        <label>Webinar Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinar Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/fields/Related_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Related_Webinar__c</fullName>
    <label>Related Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Team Members</relationshipLabel>
    <relationshipName>Webinar_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

IntelliJ Projects/SalesForceDev1/src/classes/TEST_WebinarTeamMemberTrigger.cls
/**
 * Created by nnoman on 07.07.2022.
 */

@IsTest
private class TEST_WebinarTeamMemberTrigger
{
    @IsTest
    private static void contactCannotBeAssignedToInternalWebinar()
    {
        Webinar__c webinar = new Webinar__c(Type__c='Internal');
        insert webinar;
        Contact con = new Contact(LastName='lolNOTDUPlol',MailingCountry='Poland', MailingCity='lol');
        insert con;
        Webinar_Team_Member__c wtm = new Webinar_Team_Member__c(Related_Webinar__c=webinar.Id, Contact__c=con.Id);

        DmlException de=null;
        Test.startTest();
        try
        {
//            Database.SaveResult res = Database.insert(wtm,false);
            insert wtm;
        } catch(DmlException e)
        {
            de=e;
        }
        Test.stopTest();

        System.assertNotEquals(null,de,'A DML exception should be thrown.');
//        System.assertEquals()
//        for()

    }
}