IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Registration Open</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/Webinar_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Webinar Team Member</description>
    <label>Webinar Team Member</label>
    <nameField>
        <label>Webinar Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinar Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/fields/Related_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Related_Webinar__c</fullName>
    <label>Related Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Team Members</relationshipLabel>
    <relationshipName>Webinar_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

IntelliJ Projects/SalesForceDev1/src/classes/TEST_WebinarTrigger.cls
/**
 * Created by nnoman on 07.07.2022.
 */

@IsTest
private class TEST_WebinarTrigger
{
    @IsTest
    private static void isAutomaticallyApprovedForCostBelow100()
    {
        Webinar__c webinar = new Webinar__c(Cost__c = 20);

        Test.startTest();
        Database.SaveResult result = Database.insert(webinar);
        Test.stopTest();

        webinar = [SELECT Id, Approval_Status__c FROM Webinar__c WHERE Id = :result.getId()];

//        System.assert(result.success);
        System.assertEquals('Approved', webinar.Approval_Status__c, 'Approval status should be Approved');
    }

    @IsTest
    private static void isNotAutomaticallyApprovedForCostAbove100()
    {
        Webinar__c webinar = new Webinar__c(Cost__c = 130);

        Test.startTest();
        Database.SaveResult result = Database.insert(webinar);
        Test.stopTest();

        webinar = [SELECT Id, Approval_Status__c FROM Webinar__c WHERE Id = :result.getId()];

//        System.assert(result.success);
        System.assertNotEquals('Approved', webinar.Approval_Status__c, 'Approval status should not be Approved');
    }

    @IsTest
    private static void checkIfStatusNotAllowedChangedFromNewToAnythingOtherThanCancelledWhileOnPending()
    {
        Webinar__c webinar = new Webinar__c(Status__c = 'New', Approval_Status__c = 'Pending');
        insert webinar;
        webinar.Status__c = 'Completed';
        DmlException de = null;
        try
        {
            Test.startTest();
            update webinar;
            Test.stopTest();
        } catch (DmlException e)
        {
            de = e;
        }

        System.assertNotEquals(null, de, 'An exception should be caught while updating.');
    }

    @IsTest
    private static void checkIfStatusAllowedToChangeFromNewToCancelledWhileOnPending()
    {
        Webinar__c webinar = new Webinar__c(Status__c = 'New', Approval_Status__c = 'Pending');
        insert webinar;
        webinar.Status__c = 'Cancelled';
        DmlException de = null;
        try
        {
            Test.startTest();
            update webinar;
            Test.stopTest();
        } catch (DmlException e)
        {
            de = e;
        }

        System.assertEquals(null, de, 'No exception should be caught.');
        System.assertEquals('Cancelled', webinar.Status__c, 'The approval status should be changed to cancelled.');
    }

    @IsTest
    private static void rejectedWebinarsGetCancelledStatus()
    {
        Webinar__c webinar = new Webinar__c();
        insert webinar;
        webinar.Approval_Status__c = 'Rejected';
        Test.startTest();
        update webinar;
        Test.stopTest();
        webinar = [SELECT Id, Status__c FROM Webinar__c WHERE Id = :webinar.Id];
        System.assertEquals('Cancelled', webinar.Status__c);
    }

    @IsTest
    private static void numParticipantsNotMoreThanSeats()
    {
        Webinar__c webinar = new Webinar__c(Total_Number_of_Seats__c = 1);
        DmlException de = null;
        Test.startTest();
        try
        {
            insert webinar;
            Webinar_Team_Member__c wtm = new Webinar_Team_Member__c(Related_Webinar__c=webinar.Id);
            insert wtm;
            webinar.Total_Number_of_Seats__c=0;
            update webinar;
        } catch (DmlException e)
        {
            de=e;
        }
        Test.stopTest();
        System.debug([SELECT Id, Number_of_Participants__c, Total_Number_of_Seats__c FROM Webinar__c WHERE Id = :webinar.Id]);
        System.assertNotEquals(null, de, 'DML exception should be thrown.');
    }
}