IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Price_per_Currency__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Currency__c</fullName>
    <label>Price per Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Registration Open</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/Webinar_Team_Member__c.object-meta.xml
<CustomObject>
    <description>Webinar Team Member</description>
    <label>Webinar Team Member</label>
    <nameField>
        <label>Webinar Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinar Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar_Team_Member__c/fields/Related_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Related_Webinar__c</fullName>
    <label>Related Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Team Members</relationshipLabel>
    <relationshipName>Webinar_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/WebinarEvent__e/fields/Webinar_s_Salesforce_ID__c.field-meta.xml
<CustomField>
    <fullName>Webinar_s_Salesforce_ID__c</fullName>
    <label>Webinar&apos;s Salesforce ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntelliJ Projects/SalesForceDev1/src/classes/WebinarTriggerHandler.cls
/**
 * Created by nnoman on 06.07.2022.
 */

public with sharing class WebinarTriggerHandler
{
    public static void handleBeforeInsertOrUpdate(List<Webinar__c> webinars)
    {
        calculateNumParticipants(webinars); //temporarily commented out
        checkFreeSpaces(webinars);
        calculatePricePerParticipant(webinars);
        approveCheapWebinarsAutomatically(webinars);
    }

    public static void handleBeforeUpdate(List<Webinar__c> webinars)
    {
        cancelRejectedWebinars(webinars);
    }

    public static void handleAfterInsert(List<Webinar__c> webinars)
    {
        List<WebinarEvent__e> webinarEvents = new List<WebinarEvent__e>();
        for(Webinar__c wb: webinars)
        {
            WebinarEvent__e webinarEvent = new WebinarEvent__e();
            webinarEvent.Webinar_s_Salesforce_ID__c = wb.Id;
            webinarEvents.add(webinarEvent);
        }
        //insert webinarEvents;
        //Database.insert(webinarEvents,true);
        List<Database.SaveResult> saveResults =  EventBus.publish(webinarEvents);
//        List<Id> eventIds = new List<Id>();
        for(Database.SaveResult sr : saveResults)
        {
            System.debug('Was event publishing a success? :' + sr.isSuccess());
            /*
//            if(sr.isSuccess())
//            {
//                eventIds.add(sr.getId());
//            }
*/
        }
        /*
//        List<WebinarEvent__e> listWebinarEvents = [SELECT Webinar_s_Salesforce_ID__c FROM WebinarEvent__e WHERE Id IN :eventIds LIMIT 100];
//        for(WebinarEvent__e we : listWebinarEvents)
//        {
//            System.debug(we);
//        }
*/
    }


    public static void handleBeforeUpdateWithOldMap(List<Webinar__c> webinars, Map<Id, Webinar__c>webinarMap)
    {
        for (Webinar__c wb : webinars)
        {
            Webinar__c prevWb = webinarMap.get(wb.Id);
            if (prevWb.Status__c == 'New'
                    && wb.Status__c != 'New'
                    && wb.Status__c != 'Cancelled'
                    && wb.Approval_Status__c == 'Pending')
            {
                wb.addError('Status cannot change status from New to anything except Cancelled with a Pending approval status.');
            }
        }
    }

    private static void checkFreeSpaces(List<Webinar__c> webinars)
    {
        for (Webinar__c wb : webinars)
        {
            if (wb.Number_of_Participants__c > wb.Total_Number_of_Seats__c)
            {
                wb.addError('Number of participants cannot exceed total number of seats.');
            }
        }
    }
    private static void calculateNumParticipants(List<Webinar__c> webinars)
    {
        Map<Id, Webinar__c> webinarMap = new Map<Id, Webinar__c>([SELECT Id, (SELECT Id FROM Webinar_Team_Members__r) FROM Webinar__c WHERE Id IN :webinars]);
        Boolean zeroParticipants = false;
        if (webinarMap.size() == 0)
        {
            zeroParticipants = true;
        }
        for (Webinar__c wb : webinars)
        {
            if (zeroParticipants)
            {
                wb.Number_of_Participants__c = 0;
            }
            else
            {
                Integer numTeamMembers = webinarMap.get(wb.Id).Webinar_Team_Members__r.size();
                wb.Number_of_Participants__c = numTeamMembers;
                if (numTeamMembers > wb.Total_Number_of_Seats__c)
                {
                    wb.addError('Number of team members exceeds the number of available seats.');
                }
            }
        }
    }

    private static void approveCheapWebinarsAutomatically(List<Webinar__c> webinarsToCheck)
    {
        for (Webinar__c wb : webinarsToCheck)
        {
            if (wb.Cost__c < 100 && (wb?.Approval_Status__c == 'Pending')) //what about currency though?
            {
                wb.Approval_Status__c = 'Approved';
            }
        }
    }

    private static void cancelRejectedWebinars(List<Webinar__c> webinarsToCheck)
    {
        for (Webinar__c wb : webinarsToCheck)
        {
            if (wb.Approval_Status__c == 'Rejected')
            {
                wb.Status__c = 'Cancelled';
            }
        }
    }

    private static void calculatePricePerParticipant(List<Webinar__c> webinars)
    {
        for (Webinar__c wb : webinars)
        {
            if (wb.Number_of_Participants__c != 0)
            {
                wb.Price_per_Currency__c = wb.Cost__c / wb.Number_of_Participants__c;
            }
        }
    }
}