IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Seminars conducted using the Web.</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntelliJ Projects/dev-nn-sfdx/force-app/main/default/objects/Webinar__c/fields/Price_per_Currency__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Currency__c</fullName>
    <label>Price per Currency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

IntelliJ Projects/SalesForceDev1/src/classes/WebinarCreator.cls
/**
 * Created by nnoman on 13.07.2022.
 */

public with sharing class WebinarCreator
{
    @AuraEnabled(Cacheable=false)
    public static Id createWebinar(String name, String type, Decimal cost, Decimal price)
    {
        Webinar__c webinar = new Webinar__c();

        webinar.Name=name;
        webinar.Type__c=type;
        webinar.Cost__c=cost;
        webinar.Price_per_Currency__c=price;

        insert webinar;

        return webinar.Id;
    }
}